name: Test deployment

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  verbump:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies
        run: yarn install
      - name: Run semver
        run: ./node_modules/.bin/semver main -i minor
