name: Test deployment

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  verbump:
    runs-on: ubuntu-18.04
    steps:
      - name: Run shell script
        run: ./verbump.sh
