name: Test deployment

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  verbump:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Install deps & run build
        run: yarn install && yarn build
      - name: Set TAG_VER_STRING
        run: echo '::set-output name=TAG_VER_STRING::${git describe --abbrev=0 --tags --match="main@*}'
        id: tdm
      - name: Set CURR_BRANCH
        run: echo '::set-output name=CURR_BRANCH::${git rev-parse --abbrev-ref HEAD}'
        id: bdm
      - name: Set BRANCH_TAG_VER_STRING
        run: echo '::set-output name=BRANCH_TAG_VER_STRING::${git describe --tags --abbrev=0 $CURR_BRANCH^ | grep $CURR_BRANCH}'
        id: btdm
      - name: Get data from managers
        run: echo "CURR_BRANCH is ${{ steps.bdm.outputs.CURR_BRANCH }}; BRANCH_TAG_VER_STRING is ${{ steps.btdm.outputs.BRANCH_TAG_VER_STRING }}; TAG_VER_STRING is ${{ steps.btdm.outputs.TAG_VER_STRING }};"
