name: Test deployment

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  verbump:
    runs-on: ubuntu-18.04
    steps:
      - name: PWD in place
        run: pwd && ls -lah
      - name: PWD on step back
        run: cd ../ && pwd && ls -lah
      - name: Demo code
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Run shell script
        run: ./verbump.sh
