name: Test deployment

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  verbump:
    runs-on: ubuntu-18.04
    steps:
      - name: PWD in place
        run: pwd && ls -lah
      - name: PWD on step back
        run: cd ../ && pwd && las -lah
      - name: Run shell script
        run: ./verbump.sh
