name: Test deployment

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  verbump:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Install deps
        run: yarn install
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          fetch-depth: 0
      - name: Fetch GIT tags
        run: git fetch --tags --progress
      - name: Set TAG_VER
        run: |
          TAG_VER_STRING=`git describe --abbrev=0 --tags --match="main@*"`
          TAG_VER_STRING="${TAG_VER_STRING/main@/''}"
          echo "::set-output name=TAG_VER::$TAG_VER_STRING"
        id: tdm
      - name: Set CURR_BRANCH
        run: |
          CURR_BRANCH_STRING=`git rev-parse --abbrev-ref HEAD`
          echo "::set-output name=CURR_BRANCH::$CURR_BRANCH_STRING"
        id: bdm
      - name: Set BRANCH_TAG_VER
        run: |
          BRANCH_TAG_VER_STRING=`git describe --tags --abbrev=0 ${{ steps.bdm.outputs.CURR_BRANCH }}^ | grep ${{ steps.bdm.outputs.CURR_BRANCH }}`
          echo "::set-output name=BRANCH_TAG_VER::$BRANCH_TAG_VER_STRING"
        id: btdm
      - name: Get data from managers
        run: echo "CURR_BRANCH is ${{ steps.bdm.outputs.CURR_BRANCH }}; BRANCH_TAG_VER is ${{ steps.btdm.outputs.BRANCH_TAG_VER }}; TAG_VER is ${{ steps.tdm.outputs.TAG_VER }};"
      - name: Bump new tag version
        run: |
          NEXT_VER=`./node_modules/.bin/semver ${{ steps.tdm.outputs.TAG_VER }} -i minor`
          RESULT_MSG=`git -c core.askpass=false tag -am "chore: release main-v${{ steps.tdm.outputs.TAG_VER }}" main@${{ steps.tdm.outputs.TAG_VER }}`
          echo "Next ver is $NEXT_VER"
          echo "Tag bump result is $RESULT_MSG"
          git -c core.askpass=false push --tags
